### ISSUE TITLE
Support for broadcast

### ISSUE THREAD

**Issue by johnemmanuel** [PelionIoT/java-coap#27]
Hi,

I am sorry if this is not the right place for this question. 

Does this library have support for 'broadcast'. If yes, could you please point me to a sample or documentation that could help me create a demo for CoAP broadcast. Thank you.

**Comment by szysas** [comment]
Hi @johnemmanuel 
It depends what do you mean by broadcast. If you mean multicast, then it is not supported. 
You could however implement yourself quite easily multicast transport that is based on java `MulticastSocket`.
(Sorry for late reply)

**Comment by johnemmanuel** [comment]
Hi @szysas ,

Sorry but I really did not come back to check on this. Yes I did mean multicast and I did succeed in creating a sample. Thank you for replying.
