### ISSUE TITLE
Jar on jitpack.io appears to be missing classes

### ISSUE THREAD

**Issue by mdkrajnak** [PelionIoT/java-coap#31]
When I download the 5.0.0 coap-core jar from jitpack.io it appears like the TransportExecutors class is missing so the example client does not compile.

I'm downloading via gradle, and I can confirm that the jar is downloaded and contains most of the coap-core classes, but TransportExecutors in com.mbed.coap.transport is not there.

I'm using CoapCli as a sample to try out the API but it does not compile with this class.

I want to use TLS which is new to 5.0.0 so using an older version is not an option.

I'm investigating building a copy for my own use, but I assume that if there is an issue with the jar on jitpack it would be better overall to have a complete jar available.

Thanks.

**Comment by szysas** [comment]
That version simple does not have that classs. Try to depend on commit build, for example: 

```
dependencies {
	        implementation 'com.github.ArmMbed:java-coap:9cd9e8141b'
	}
```
