### ISSUE TITLE
Is this project active ?

### ISSUE THREAD

**Issue by sbernard31** [PelionIoT/java-coap#58]
Hi,

**Some questions :**

I would like to know if this project is still actively maintain ?

@szysas I also discover there was a project to integrate CoAP in OpenJDK named Kona. I saw that [you contribute code to this project](https://hg.openjdk.java.net/kona/coap/rev/dcef39bd7c57) but I understand the kona project is not active anymore, correct ? Could you share a bit what happens ? 

**Some context :** 

I'm the main maintainer of [Leshan](https://github.com/eclipse/leshan) project (LWM2M implementation for java).
Leshan is mainly based on [Californium](https://github.com/eclipse-californium/californium) for coap.
Recently I try to [abstract the transport layer of Leshan](https://github.com/eclipse/leshan/issues/1025) to be able to add new implementation based on different protocol (e.g. mqtt) or different CoAP library.
We currently search what protocol/library we should use to test this abstraction. (https://github.com/eclipse/leshan/issues/1338)

**Comment by sbernard31** [comment]
Thx for the prompt answer.

Do not hesitate to stop me if some of my questions are too personal.

> As I don't work anymore for Pelion, I don't know what is the status of this project.

Looking at the activity about commit / issue / release. It seems you were the last active contributor.
So I guess if you don't work anymore on this project we can consider this project is not active anymore.

But glad to see, it exists an actively maintained fork of this one. 

Should it be better to add a message in the README or/and in a pinned issue explaining that this project is no more active and then redirect to the fork ? 
(Maybe I was not so good but I didn't find the fork by myself)
We can wait if some one from Pelion answer or maybe try to ping someone who seems to be active in this [Pelion organization](https://github.com/PelionIoT)  but if we get no answer, I really think this will be better for everyone to clarify the situation.
If later, someone finally wake up, this will still be possible to update again the README and/or close this issue explaining the current state of the project. 

The project was initially managed by PelionIoT ? I don't know why by I was thinking that ARM was involved in this ? Did I miss something ?

> Regardless project Kona, it looks like it never went off, but I don't know why.

I'm very curious about this, , do you know someone I could contact to know more about this ? 

>  Anyway, I have made a fork (https://github.com/open-coap/java-coap) which is actively maintained and developed.

Are you maintaining this fork on your personal free time or this is part of your day to day work ?
Should we continue this discussion in the maintained fork ?

> I'd be happy to help (if needed) with integration work with Leshan abstractions. (BTW, sounds like a good idea +1)

Thx to propose your help. :pray: 
We try to build community around Leshan so help is welcomed !
Just to be sure : 
1. do you propose support to help us when we face issue about how to use java-coap 
2. or would you like to be involved directly in implementation, I mean like written code or review PR
3. or maybe you have something else in mind ?

**Comment by szysas** [comment]
Integration part we can continue discussion on a fork repo. 
I meant that I can help with integration java-coap with leshan, and adjust java-coap API to make it easier with integration. 

If you wish, we could talk more on private channel (for example LinkedIn: www.linkedin.com/in/szymon-sasin-0627802a)

**Comment by szysas** [comment]
@JanneKiiskila are you able to answer some of these questions?

**Comment by JanneKiiskila** [comment]
This will be maintained with some effort (security fixes and so forth). But, for the Leshan project it probably looks like a better match to use the fork Szymon [open-coap/java-coap](https://github.com/open-coap/java-coap) has created as he seems to have a lot more bandwidth.

**Comment by sbernard31** [comment]
@JanneKiiskila thx for your answer :pray: 

> This will be maintained with some effort (security fixes and so forth). 

Just to be sure, it is not maintained for now but you plan to do it at short/mid term  but with minimal effort ?

I'm not sure to get the rational behind this ? :thinking: 

Could I friendly ask why not :
 - just officially stop the project,
 - use the new java-coap fork for you needs too
 - also redirect current and new users to the fork. (You already do this one in previous message but I have in mind something more visible/official) 

Maybe this is because you are still using this project in a not so active project and don't want to handle eventual current or future API break ? :thinking:

**Comment by JanneKiiskila** [comment]
We are still using this project in our side. The API changes on @szysas side is something that makes the integration effort perhaps not so trivial, so we will not abandon this project. However, people looking for a more aggressively developed solution are perhaps better of using the repository  @szysas is maintaining.

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/java-coap/pull/60 should cover the README.md update request @sbernard31 would you agree?

**Comment by sbernard31** [comment]
Yes I think this clarifies the situation. 

Thx for handling this @JanneKiiskila :pray:
